version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: contract_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: contract
      MYSQL_USER: contract_user
      MYSQL_PASSWORD: contract_password
    ports:
      - "8082:3306"  # Host port 8081 maps to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - contract_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: contract_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"  # Access phpMyAdmin at http://localhost:8080
    depends_on:
      - mysql
    networks:
      - contract_network
volumes:
  mysql_data:
networks:
  contract_network:
    driver: bridge